#!/usr/bin/env python3

import sys

from converter import LinkConverter
from file_scanner import FileScanner
from valid_path import PATH_VALIDITY, interpret_results, is_valid_path


def usage():
    print("Usage: main.py <dir_path>")
    sys.exit(1)


class MassConvert:
    def __init__(self, dir_path: str):
        self.files: list[str] = FileScanner(dir_path).get_all_files()
        self.converter: LinkConverter = LinkConverter()
        self.convert_files()

    def convert_files(self) -> None:

        count:int = 1
        
        for file in self.files:
            is_valid_file:PATH_VALIDITY = is_valid_path(file)
            interpret_results(is_valid_file)

            with open(file, "r", encoding="utf-8") as f:
                content = f.read()

            content = self.converter.convert_markdown_to_wikilink(content)

            with open(file, "w", encoding="utf-8") as f:
                _ = f.write(content)

            print(f"{count}. {file} was Successfully converted and changes has been saved.")
            count+=1

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(sys.argv)
        usage()

    dir_path: str = sys.argv[1]
    MassConvert(dir_path)
